config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'

  root 'welcome#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  # user sessions and clearance
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  #user facebook omniauth and edit
  resources :users, only: [:show, :index]
  get "/auth/:provider/callback", to: "sessions#create_from_omniauth", as:"fb"
  patch "/users/:id", to: "users#edit", as: "edit_user"

  #listings
  resources :users do
    resources :listings, only: [:edit,:update]
  end
  resources :listings, except: [:edit, :update]

  resources :listings do
    resources :reservations, only: [:new, :create, :show, :index]
  end

  resources :reservations do
    resources :braintree, only: :new
  end
  post 'braintree/checkout'

  get '/my_trips', to: "reservations#index", as: "my_reservations"
  get '/users/:user_id/reservations/:id', to: "reservations#show", as: "my_reservation"

  # patch '/reservations/:reservation_id', to: "reservation#update_request"

end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController

  def new
    @client_token = Braintree::ClientToken.generate
  end

  def checkout
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

    result = Braintree::Transaction.sale(
     :amount => "10.00", #this is currently hardcoded
     :payment_method_nonce => nonce_from_the_client,
     :options => {
        :submit_for_settlement => true
      }
     )

    if result.success?
      redirect_to :root, :flash => { :success => "Transaction successful!" }
    else
      redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
    end
  end

end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/views/braintree/new.html.erb
<center>
  <h2> Congratulation! Your request has been approved by the host </h2>
  <p id='paymeny-method'> Just one more step to rent this place </p>
</center>
<div class="demo-frame">
<%= hidden_field_tag :token, @client_token %>
    <%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "cardForm"} do |form| %>
        <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
        <div id="card-number" class="hosted-field"></div>

        <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
        <div id="expiration-date" class="hosted-field"></div>

        <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
        <div id="cvv" class="hosted-field"></div>

        <%= form.hidden_field "payment_method_nonce" %>

        <div class="button-container">
          <%= form.submit "Purchase", class: "btn btn-primary", id: "submit-payment-btn" %>
        </div>
    <% end %>
</div>

<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
<% end %>