config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'

  root 'welcome#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  # user sessions and clearance
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  #user facebook omniauth and edit
  resources :users, only: [:show, :index]
  get "/auth/:provider/callback", to: "sessions#create_from_omniauth", as:"fb"
  patch "/users/:id", to: "users#edit", as: "edit_user"

  #listings
  resources :users do
    resources :listings, only: [:edit,:update]
  end
  resources :listings, except: [:edit, :update]

  resources :listings do
    resources :reservations, only: [:new, :create, :show, :index]
  end

  resources :reservations do
    resources :braintree, only: :new
  end
  post 'braintree/checkout'

  get '/my_trips', to: "reservations#index", as: "my_reservations"
  get '/users/:user_id/reservations/:id', to: "reservations#show", as: "my_reservation"

  # patch '/reservations/:reservation_id', to: "reservation#update_request"

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  # validates :passport_number, :phone_number, uniqueness: true
  validates :email, uniqueness:{ message: "Your email has already been taken!"}
  validates :email, presence: { message: "You need to type in an email!"}

  has_many :authentications, :dependent => :destroy
  has_many :listings, :dependent => :destroy
  has_many :reservations

  enum role: ['user', 'moderate', 'superadmin']
  mount_uploader :avatar, AvatarUploader


  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      # u.first_name = auth_hash["info"]["first_name"]
      # u.last_name = auth_hash["info"]["last_name"]
      # u.friendly_name = auth_hash["info"]["name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.password = SecureRandom.hex(6)
      u.authentications<<(authentication)
    end

  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = User.new
    render template: "users/new"
  end

  def create
    byebug
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to user_path(@user)
    else
      @message = @user.errors.full_messages
      render :json => @message.to_json
      # byebug
      # respond_to do |format|
      #   # format.html
      #   format.json{ render :json => @message.to_json }
      # end
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_params
    params.require(:user).permit(:email, :password, :name, :age, :first_name, :last_name, :phone_number, :passport_number, :city, :nationality, :currency, :role, :avatar)

    # email = user_params.delete(:email)
    # password = user_params.delete(:password)
    #
    # Clearance.configuration.user_model.new(user_params).tap do |user|
    #   user.email = email
    #   user.password = password
    # end
  end

  # def user_params

  #   params[Clearance.configuration.user_parameter] || Hash.new
  # end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def edit
    #user
    @user = current_user
    #superadmin
    @user_role = User.find(params[:id])

    #edit profile user
    if current_user.role == 'user'
      if @user.update(user_params)
        redirect_to root_path
      else
        redirect_to user_path(@user)
      end
    #edit user role by superadmin
    elsif current_user.role =='superadmin'
      if @user_role.update(user_params)
        redirect_to root_path
      else
        redirect_to user_path(@user)
      end
    end
  end

  # def update
  #   #user
  #   @user = current_user
  #   #superadmin
  #   @user_role = User.find(params[:id])
  #
  #   #edit profile user
  #   if current_user.role == 'user'
  #     if @user.update(user_params)
  #       redirect_to root_path
  #     else
  #       redirect_to user_path(@user)
  #     end
  #   #edit user role by superadmin
  #   elsif current_user.role =='superadmin'
  #     if @user_role.update(user_params)
  #       redirect_to root_path
  #     else
  #       redirect_to user_path(@user)
  #     end
  #   end
  # end

  def show
    @user = current_user
    @user_role = User.find(params[:id])
    # render "welcome/edit"
  end

  def index
    allowed?(action: :index, user: current_user)
    @counter ||= 0 unless @counter
    @users = User.all
    if params[:value] == nil
      @users_per_page = User.all.order(:id).limit(10).offset(@counter)
    else
      @counter += params[:value].to_i
      @users_per_page = User.all.order(:id).limit(10).offset(@counter)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!-- <div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
  <div id="emailErrors">
  </div>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="text-field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name %>
</div>

<div class="password-field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name %>
</div>

<div class="password-field">
  <%= form.label :phone_number %>
  <%= form.text_field :phone_number %>
</div>

<div class="password-field">
  <%= form.label :passport_number %>
  <%= form.text_field :passport_number %>
</div>

<div class="password-field">
  <%= form.label :city %>
  <%= form.text_field :city %>
</div> -->

<div class="row">
    <div class="col-xs-6 col-md-6">
        <%= form.text_field :first_name, class: "form-control", placeholder: "First Name", required: true, autofocus: true%>
    </div>
    <div class="col-xs-6 col-md-6">
        <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name", required: true, autofocus: true%>
    </div>
</div>

<%= form.text_field :email, type: 'email', class: 'form-control', placeholder: 'Your Email' %>
<%= form.password_field :password, class: 'form-control', placeholder: 'Your Password' %>
<%= password_field_tag :password_confirmation, nil, class: "form-control", placeholder: 'Re-Enter Password' %>

<div class="form-group">
  <%= form.label :birthday %>
  <%= form.date_select :birthday %>
</div>
<div class="form-group">
  <%= form.label :gender %>
  <%= form.select :gender do %>
      <option value="1">Male</option>
      <option value="2">Female</option>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container-fluid" style="background-color:#e8e8e8">
  <div class="container container-pad" id="property-listings">

      <div class="row">
          <div class="col-sm-12">
            <% @users_per_page.each do |user| %>
              <!-- Begin Listing: 609 W GRAVERS LN-->
              <div class="brdr bgc-fff pad-10 box-shad btm-mrg-20 property-listing">
                  <div class="media">
                      <a class="pull-left" href="#" target="_parent">
                      <%= image_tag 'default-picture-property.jpg', :class=> 'img-responsive', :alt=> 'image'%>
                      </a>

                      <div class="clearfix visible-sm"></div>

                      <div class="media-body fnt-smaller">
                          <a href="#" target="_parent"></a>

                          <h4 class="media-heading">
                            <a href="/users/<%=user.id%>" target="_parent"><%= user.first_name %>,<%=user.last_name%></a>
                          </h4>

                          <p> <%=user.email %> </p>


                          <p class="hidden-xs"><%=user.role%></p><span class="fnt-smaller fnt-lighter fnt-arial"></span>
                      </div>
                  </div>
              </div><!-- End Listing-->
            <%end%>
            <%if @users_per_page.first.id == @users.first.id %>
                <div class='col-sm-1'>
                </div>
                <div class='col-sm-10'>
                </div>
                <div class='col-sm-1'>
                  <%=form_tag users_path, method: :get do %>
                    <%= hidden_field_tag "value", 10 %>
                    <%= submit_tag ">" %>
                  <% end%>
                </div>
            <%elsif @users_per_page.last.id == @users.last.id%>
              <%=form_tag users_path, method: :get do %>
                <%= hidden_field_tag "value",  @counter - 10 %>
                <%= submit_tag "<" %>
              <% end%>
            <%else%>
              <div class='col-sm-1'>
                <%=form_tag users_path, method: :get do %>
                  <%= hidden_field_tag "value",  @counter - 10 %>
                  <%= submit_tag "<" %>
                <% end%>
              </div>
              <div class='col-sm-10'>
              </div>
              <div class='col-sm-1'>
                <%=form_tag users_path, method: :get do %>
                  <%= hidden_field_tag "value",  @counter + 10 %>
                  <%= submit_tag ">" %>
                <% end%>
              </div>
            <%end%>
          </div><!-- End Col -->
      </div><!-- End row -->
  </div><!-- End container -->
</div>

app/views/users/new.html.erb
<center>
  <div id='dashboard-header'>
    <a href="/"><%= image_tag 'bearbnb-logo.png', :id => 'header-logo' %></a>
    <p id='tag-line-home'> Welcome to Bearbnb! Start your adventure with us </p>
  </div>
</center>

<!-- <div class="col-xs-8 col-sm-8 col-md-8 col-xs-offset-2 col-sm-offset-2 col-md-offset-2" align-items='center'> -->
  <div class="container" id='sign-up-container'>
      <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-4">
          </div>
          <div class="col-xs-12 col-sm-12 col-md-4 well well-sm">
              <legend><a href="http://www.jquery2dotnet.com"><i class="glyphicon glyphicon-globe"></i></a> Sign up!</legend>
              <center>
                <div id="clearance" class="sign-up">
                  <h2><%= t(".title") %></h2>

                  <%= form_for @user do |form| %>
                    <%= render partial: '/users/form', object: form %>

                    <div class="submit-field">
                      <%= form.submit class: "btn btn-success" %>
                    </div>
                  <% end %>
                  <div class="other-links">
                    <%= link_to t(".sign_in"), sign_in_path %>
                  </div>
                </div>
              </center>
          </div>
      </div>
  </div>
<!-- </div> -->

app/views/users/show.html.erb
<center>
  <div id='dashboard-header'>
    <a href="/"><%= image_tag 'bearbnb-logo.png', :id => 'header-logo' %></a>
  </div>
</center>


<%if current_user.role == 'user'%>
    <div class="container">
        <%= form_for @user do |f|%>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
              <div class="panel panel-default">
                <div class="panel panel-primary">
                  <h4 class="text-center">Update your information for access to book and rent places</h4>
                  <div class="panel-body">

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span>
                            </span>
                            <%= f.text_field :first_name, :class=> "form-control", :placeholder => "First Name" %>
                            <!-- <input type="text" class="form-control" name= "user[first_name]" placeholder="First Name" /> -->
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                            <%= f.text_field :last_name, :class=> "form-control", :value => "#{current_user.last_name}", :placeholder => "Last Name"  %>
                            <!-- <input type="text" class="form-control" placeholder="Last Name" /> -->
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-book"></span></span>
                            <%= f.text_field :passport_number, :class=> "form-control", :value => "#{current_user.passport_number}", :placeholder => "Passport Number"  %>
                            <!-- <input type="text" class="form-control" placeholder="Email" /> -->
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-phone"></span></span>
                            <%= f.text_field :phone_number, :class=> "form-control", :value => "#{current_user.phone_number}", :placeholder => "Phone Number"  %>
                            <!-- <input type="password" class="form-control" placeholder="New Password" /> -->
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-globe"></span></span>
                            <%= f.text_field :nationality, :class=> "form-control", :value => "#{current_user.nationality}", :placeholder => "Nationality"  %>
                            <!-- <input type="text" class="form-control" placeholder="Address" /> -->
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-map-marker"></span></span>
                            <%= f.text_field :city, :class=> "form-control", :value => "#{current_user.city}", :placeholder => "Address(city)" %>
                            <!-- <input type="text" class="form-control" placeholder="Age" /> -->
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-credit-card"></span></span>
                            <%= f.text_field :currency, :class=> "form-control", :value => "#{current_user.currency}", :placeholder => "Currency"  %>
                            <!-- <input type="text" class="form-control" placeholder="Credit card" /> -->
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <%= f.file_field :avatar, :class=> "form-control"%>
                        </div>
                    </div>


                    <button class="btn btn-lg btn-primary btn-block" type="submit">Save</button>
                  <!-- panel body -->
                  </div>
              <!-- panel panel primary   -->
               </div>
            <!-- panel panel default, -->
            </div>
    <!-- col-md-4 col-md-offset-4"> -->
          </div>
          <!-- row -->
        </div>
      <%end%>
    <!-- container -->
    </div>


<% else %>

    <div class="container">
        <%= form_for @user_role do |f|%>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
              <div class="panel panel-default">
                <div class="panel panel-primary">
                  <h4 class="text-center">Change his Role</h4>
                  <div class="panel-body">

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span>
                            </span>
                            <%= f.text_field :first_name, :class=> "form-control", :placeholder => "First Name", :disabled => true%>
                            <!-- <input type="text" class="form-control" name= "user[first_name]" placeholder="First Name" /> -->
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                            <%= f.text_field :last_name, :class=> "form-control", :placeholder => "Last Name", :disabled => true  %>
                            <!-- <input type="text" class="form-control" placeholder="Last Name" /> -->
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-book"></span></span>
                            <%= f.text_field :passport_number, :class=> "form-control", :placeholder => "Passport Number", :disabled => true  %>
                            <!-- <input type="text" class="form-control" placeholder="Email" /> -->
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-phone"></span></span>
                            <%= f.text_field :phone_number, :class=> "form-control", :placeholder => "Phone Number", :disabled => true  %>
                            <!-- <input type="password" class="form-control" placeholder="New Password" /> -->
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-globe"></span></span>
                            <%= f.text_field :nationality, :class=> "form-control", :value => "#{current_user.nationality}", :placeholder => "Nationality", :disabled => true  %>
                            <!-- <input type="text" class="form-control" placeholder="Address" /> -->
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-map-marker"></span></span>
                            <%= f.text_field :city, :class=> "form-control", :placeholder => "Address(city)", :disabled => true %>
                            <!-- <input type="text" class="form-control" placeholder="Age" /> -->
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-credit-card"></span></span>
                            <%= f.text_field :currency, :class=> "form-control", :placeholder => "Currency", :disabled => true  %>
                            <!-- <input type="text" class="form-control" placeholder="Credit card" /> -->
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-credit-card"></span></span>
                            <%= f.text_field :role, :class=> "form-control", :placeholder => "Role"  %>
                            <!-- <input type="text" class="form-control" placeholder="Credit card" /> -->
                        </div>
                    </div>


                    <button class="btn btn-lg btn-primary btn-block" type="submit">Save</button>
                  <!-- panel body -->
                  </div>
              <!-- panel panel primary   -->
               </div>
            <!-- panel panel default, -->
            </div>
    <!-- col-md-4 col-md-offset-4"> -->
          </div>
          <!-- row -->
        </div>
      <%end%>
    <!-- container -->
    </div>
<% end %>