config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'

  root 'welcome#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  # user sessions and clearance
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  #user facebook omniauth and edit
  resources :users, only: [:show, :index]
  get "/auth/:provider/callback", to: "sessions#create_from_omniauth", as:"fb"
  patch "/users/:id", to: "users#edit", as: "edit_user"

  #listings
  resources :users do
    resources :listings, only: [:edit,:update]
  end
  resources :listings, except: [:edit, :update]

  resources :listings do
    resources :reservations, only: [:new, :create, :show, :index]
  end

  resources :reservations do
    resources :braintree, only: :new
  end
  post 'braintree/checkout'

  get '/my_trips', to: "reservations#index", as: "my_reservations"
  get '/users/:user_id/reservations/:id', to: "reservations#show", as: "my_reservation"

  # patch '/reservations/:reservation_id', to: "reservation#update_request"

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  # before_create :set_bookings_date
  before_create :set_total_price

  validates :start_date, :end_date, presence: true

  belongs_to :user
  belongs_to :listing



  def date_confirmation
    # byebug
    self.start_date < self.end_date
  end

  def set_total_price
    self.total_price = (self.start_date..self.end_date).to_a.length * self.listing.price
  end

  def overlap?(reservation,booking)
    (reservation.start_date - booking.end_date) * (booking.start_date - reservation.end_date) > 0
  end

  def available_dates?(listing_dates)
    (self.start_date..self.end_date).each do |date|
      return false if !(listing_dates.start_date..listing_dates.end_date).include?(date)
    end
    return true
  end

  def overlap_dates?(bookings)
    bookings.each do |x|
      return true if overlap?(self,x)
    end
    return false
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def new

  end

  def create
    @listing = Listing.find(params[:listing_id])
    a = Date.strptime(params[:reservation][:start_date],'%m/%d/%Y')
    b = Date.strptime(params[:reservation][:end_date],'%m/%d/%Y')

    @reservation = current_user.reservations.new(start_date: a, end_date: b)

    if @reservation.date_confirmation && !@reservation.overlap_dates?(@listing.reservations) && @reservation.available_dates?(@listing)
      @reservation.listing_id = @listing.id
      if @reservation.save
        ReservationMailersJob.perform_now(@reservation)
        # ReservationMailer.booking_created_customer_email(@reservation).deliver_now
        # ReservationMailer.booking_created_host_email(@reservation).deliver_now

        redirect_to '/'
      else
        redirect_to listings_path(Listing.find(params[:id]))
      end
    else
      flash[:error] = "Reservation failed"
      redirect_to listing_path(@listing)
    end
  end

  def show
    if params[:listing_id]
      @reservation = Listing.find(params[:listing_id]).reservations.find(params[:id])
    else
      @reservation = current_user.reservations.find(params[:id])
    end
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.request_status.nil?
      @reservation.request_status = params[:reservation][:request_status]
      if @reservation.save
        redirect_to '/'
      end
    end

  end

  def index
    if params[:listing_id]
      @reservations = Listing.find(params[:listing_id]).reservations
    else
      @reservations = current_user.reservations
    end
  end

  private
  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :rating, :comment, :user_id, :listing_id)
  end

end

app/views/reservations/index.html.erb
<table class ="table">
<tr>
  <th>Start Date</th>
  <th>End Date</th>
</tr>
<% @reservations.each do |r| %>
<tr>
  <td><%= r.start_date %></td>
  <td><%= r.end_date %></td>
</tr>
<% end %>

</table>

app/views/reservations/show.html.erb
<div class='col-md-8 col-xs-8 col-sm-8 col-md-offset-2 col-xs-offset-2 col-sm-offset-2'>
  <div>
    <center>
      <%= image_tag current_user.avatar.thumb%>
    </center>
  </div>
</div>

<div class='col-md-8 col-xs-8 col-sm-8 col-md-offset-2 col-xs-offset-2 col-sm-offset-2' id='reservation-request-details'>

  <div class='col-md-6 col-xs-6 col-sm-6'>

    <div id='reservation-dates'>
      <p> Reservation Details </p>
      <div class='col-md-6 col-xs-6 col-sm-6'>
        <div class='row'>
          <p> CHECK IN DATE </p>
          <%= @reservation.start_date %>
        </div>
      </div>

      <div class='col-md-6 col-xs-6 col-sm-6'>
        <div class='row'>
          <p> CHECK OUT DATE </p>
          <%= @reservation.end_date %>
        </div>
      </div>
    </div>

    <div id='reservation-price'>
      <p> TOTAL PRICE </p>
      <%=@reservation.total_price %>
    </div>


  </div>

  <div class='col-md-6 col-xs-6 col-sm-6'>
    <p> Customer Details </p>
    <p> Name : <%=@reservation.user.first_name%></p>
    <p> City : <%=@reservation.user.city%> </p>
    <p> Nationality: <%=@reservation.user.nationality%></p>

  </div>

</div>

<div class='col-md-8 col-xs-8 col-sm-8 col-md-offset-2 col-xs-offset-2 col-sm-offset-2'>

  <div class='col-md-6 col-xs-6 col-sm-6'>
    <% if current_user == @reservation.listing.user%>
      <div class='col-md-6 col-xs-6 col-sm-6'>
        <%=form_for @reservation do |form| %>
          <%= form.hidden_field :request_status, value: true %>
          <%= form.submit 'Accept', class: 'btn btn-success' %>
        <% end %>
      </div>
      <div class='col-md-6 col-xs-6 col-sm-6'>
        <%=form_for @reservation do |form| %>
          <%= form.hidden_field :request_status, value: false %>
          <%= form.submit 'Decline', class: 'btn btn-danger' %>
        <% end %>
      </div>
    <% else %>
      <% if @reservation.request_status.nil? %>
          <p> We have sent your request to the host </p>
          <p> Please wait :) </p>
      <% elsif @reservation.request_status == true %>
          <%= button_to "Payment", new_reservation_braintree_path(@reservation), :id => "open-contacts-dialog-btn", :class => "inbox-sf-add-btn tip", :method => :get %>
      <% else %>
          <p> We are sorry, your request has been rejected by the host </p>
      <% end %>

    <% end %>
  </div>
  <% if current_user == @reservation.listing.user%>
  <% end %>

  <div class='col-md-6 col-xs-6 col-sm-6'>
  </div>

</div>