config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'

  root 'welcome#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  # user sessions and clearance
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  #user facebook omniauth and edit
  resources :users, only: [:show, :index]
  get "/auth/:provider/callback", to: "sessions#create_from_omniauth", as:"fb"
  patch "/users/:id", to: "users#edit", as: "edit_user"

  #listings
  resources :users do
    resources :listings, only: [:edit,:update]
  end
  resources :listings, except: [:edit, :update]

  resources :listings do
    resources :reservations, only: [:new, :create, :show, :index]
  end

  resources :reservations do
    resources :braintree, only: :new
  end
  post 'braintree/checkout'

  get '/my_trips', to: "reservations#index", as: "my_reservations"
  get '/users/:user_id/reservations/:id', to: "reservations#show", as: "my_reservation"

  # patch '/reservations/:reservation_id', to: "reservation#update_request"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bearbnb</title>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://opensource.keycdn.com/fontawesome/4.6.3/font-awesome.min.css"
    integrity="sha384-Wrgq82RsEean5tP3NK3zWAemiNEXofJsTwTyHmNb/iL3dP/sZJ4+7sOld1uqYJtE" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <!-- <%= link_to "Home", root_path, class: "btn btn-default" %> -->
  <%if signed_in? %>
    <body>
			<nav class="navbar navbar-default">
			  <div class="container-fluid">
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			    </div>
			    <div class="collapse navbar-collapse" id="myNavbar">
			      <ul class="nav navbar-nav">
			        <li class="active"><a class='header-btns' id='home-btn' href="/">HOME</a></li>
			      </ul>

            <form class="navbar-form navbar-left" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>

              <ul class="nav navbar-nav navbar-right">
                <li class="dropdown thumb-dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= image_tag "#{current_user.avatar.thumb}", id: 'thumbnail'%> <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li role="presentation" class="dropdown-header"><%=current_user.first_name%></li>
                    <li>
                        <%= link_to 'Sign out', sign_out_path, method: :delete %>
                    </li>
                    <li>
                      <a class='header-btns' id='home-btn' href="/users/<%=current_user.id%>">Profile</a>

                    </li>
                    <li>

                    </li>

                    <li>

                    </li>
                  </ul>
                </li>
              </ul>

              <ul class="nav navbar-nav navbar-right">
  			        <li>
                  <a class='header-btns' id='home-btn' href="/my_trips">
                    <p class='header-menu'>My Trips</p>
                  </a>
                </li>
  			      </ul>

              <ul class="nav navbar-nav navbar-right">
  			        <li>
                  <a class='header-btns' id='home-btn' href="/listings/new">
                    <p class='header-menu'>Become a Host</p>
                  </a>
                </li>
  			      </ul>


            <% if current_user.role == 'superadmin'%>
              <ul class="nav navbar-nav navbar-right">
  			        <li><a class='header-btns' id='home-btn' href="/users">Super Admin</a></li>
  			      </ul>
            <%end%>


			    </div>
			  </div>
			</nav>

      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>

      <%= yield %>
    </body>

  <% else %>
    <body id='session-background'>
      <% if signed_in? %>
        Signed in as: <%= current_user.email %>
        <%= button_to 'Sign out', sign_out_path, method: :delete %>
      <% end %>

      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>

      <%= yield %>
    </body>

  <% end %>
</html>